export interface DeckCard {
  id: string;
  suit: 'major' | 'wands' | 'cups' | 'swords' | 'pentacles';
  name: string;
}

export const DECK: DeckCard[] = [
  // ==== ARCANOS MAYORES ====
  { id: 'elmag0', suit: 'major', name: 'El Mago' },
  { id: 'lagransacerdotisa', suit: 'major', name: 'La Gran Sacerdotisa' },
  { id: 'laemperatriz', suit: 'major', name: 'La Emperatriz' },
  { id: 'elemperador', suit: 'major', name: 'El Emperador' },
  { id: 'elpapa', suit: 'major', name: 'El Papa' },
  { id: 'losenamorados', suit: 'major', name: 'Los enamorados' },
  { id: 'elcarro', suit: 'major', name: 'El Carro' },
  { id: 'elermitaño', suit: 'major', name: 'El Ermitaño' },
  { id: 'lafuerza', suit: 'major', name: 'La Fuerza' },
  { id: 'elcolgado', suit: 'major', name: 'El Colgado' },
  { id: 'eljusticia', suit: 'major', name: 'La Justicia' },
  { id: 'laemperatriz', suit: 'major', name: 'La Emperatriz' },
  { id: 'latemplanza', suit: 'major', name: 'La Templanza' },
  { id: 'eldiablo', suit: 'major', name: 'El Diablo' },
  { id: 'latorre', suit: 'major', name: 'La Torre' },
  { id: 'laestrella', suit: 'major', name: 'La Estrella' },
  { id: 'laluna', suit: 'major', name: 'La Luna' },
  { id: 'elsol', suit: 'major', name: 'El Sol' },
  { id: 'eljuicio', suit: 'major', name: 'El Juicio' },
  { id: 'elmundo', suit: 'major', name: 'El Mundo' },
  { id: 'elloco', suit: 'major', name: 'El Loco' },

  // ==== BASTOS ====
  { id: 'asdebastos', suit: 'wands', name: 'As de Bastos' },
  { id: 'dosdebastos', suit: 'wands', name: 'Dos de Bastos' },
  { id: 'tresdebastos', suit: 'wands', name: 'Tres de Bastos' },
  { id: 'cuatrodebastos', suit: 'wands', name: 'Cuatro de Bastos' },
  { id: 'cincodebastos', suit: 'wands', name: 'Cinco de Bastos' },
  { id: 'seisdebastos', suit: 'wands', name: 'Seis de Bastos' },
  { id: 'sietedebastos', suit: 'wands', name: 'Siete de Bastos' },
  { id: 'ochodebastos', suit: 'wands', name: 'Ocho de Bastos' },
  { id: 'nuevedebastos', suit: 'wands', name: 'Nueve de Bastos' },
  { id: 'diezdebastos', suit: 'wands', name: 'Diez de Bastos' },
  { id: 'pagedebastos', suit: 'wands', name: 'Paje de Bastos' },
  { id: 'caballerodebastos', suit: 'wands', name: 'Caballero de Bastos' },
  { id: 'reinadebastos', suit: 'wands', name: 'Reina de Bastos' },
  { id: 'reydebastos', suit: 'wands', name: 'Rey de Bastos' },

  // ==== COPAS ====
  { id: 'asdecopas', suit: 'cups', name: 'As de Copas' },
  { id: 'dosdecopas', suit: 'cups', name: 'Dos de Copas' },
  { id: 'tresdecopas', suit: 'cups', name: 'Tres de Copas' },
  { id: 'cuatrodecopas', suit: 'cups', name: 'Cuatro de Copas' },
  { id: 'cincodecopas', suit: 'cups', name: 'Cinco de Copas' },
  { id: 'seisdecopas', suit: 'cups', name: 'Seis de Copas' },
  { id: 'sietedecopas', suit: 'cups', name: 'Siete de Copas' },
  { id: 'ochodecopas', suit: 'cups', name: 'Ocho de Copas' },
  { id: 'nuevedecopas', suit: 'cups', name: 'Nueve de Copas' },
  { id: 'diezdecopas', suit: 'cups', name: 'Diez de Copas' },
  { id: 'pagedecopas', suit: 'cups', name: 'Paje de Copas' },
  { id: 'caballerodecopas', suit: 'cups', name: 'Caballero de Copas' },
  { id: 'reinadecopas', suit: 'cups', name: 'Reina de Copas' },
  { id: 'reydecopas', suit: 'cups', name: 'Rey de Copas' },

  // ==== ESPADAS ====
  { id: 'asdeespadas', suit: 'swords', name: 'As de Espadas' },
  { id: 'dosdeespadas', suit: 'swords', name: 'Dos de Espadas' },
  { id: 'tresdeespadas', suit: 'swords', name: 'Tres de Espadas' },
  { id: 'cuatrodeespadas', suit: 'swords', name: 'Cuatro de Espadas' },
  { id: 'cincodeespadas', suit: 'swords', name: 'Cinco de Espadas' },
  { id: 'seisdespadas', suit: 'swords', name: 'Seis de Espadas' },
  { id: 'sietedeespadas', suit: 'swords', name: 'Siete de Espadas' },
  { id: 'ochodeespadas', suit: 'swords', name: 'Ocho de Espadas' },
  { id: 'nuevedeespadas', suit: 'swords', name: 'Nueve de Espadas' },
  { id: 'diezdeespadas', suit: 'swords', name: 'Diez de Espadas' },
  { id: 'pagedeespadas', suit: 'swords', name: 'Paje de Espadas' },
  { id: 'caballerodeespadas', suit: 'swords', name: 'Caballero de Espadas' },
  { id: 'reinadeespadas', suit: 'swords', name: 'Reina de Espadas' },
  { id: 'reydeespadas', suit: 'swords', name: 'Rey de Espadas' },

  // ==== PENTÁCULOS ====
  { id: 'asdepentaculos', suit: 'pentacles', name: 'As de Pentáculos' },
  { id: 'dosdepentaculos', suit: 'pentacles', name: 'Dos de Pentáculos' },
  { id: 'tresdepentaculos', suit: 'pentacles', name: 'Tres de Pentáculos' },
  { id: 'cuatrodepentaculos', suit: 'pentacles', name: 'Cuatro de Pentáculos' },
  { id: 'cincodepentaculos', suit: 'pentacles', name: 'Cinco de Pentáculos' },
  { id: 'seisdepentaculos', suit: 'pentacles', name: 'Seis de Pentáculos' },
  { id: 'sietedepentaculos', suit: 'pentacles', name: 'Siete de Pentáculos' },
  { id: 'ochodepentaculos', suit: 'pentacles', name: 'Ocho de Pentáculos' },
  { id: 'nuevedepentaculos', suit: 'pentacles', name: 'Nueve de Pentáculos' },
  { id: 'diezdepentaculos', suit: 'pentacles', name: 'Diez de Pentáculos' },
  { id: 'pagedepentaculos', suit: 'pentacles', name: 'Paje de Pentáculos' },
  { id: 'caballerodepentaculos', suit: 'pentacles', name: 'Caballero de Pentáculos' },
  { id: 'reinadepentaculos', suit: 'pentacles', name: 'Reina de Pentáculos' },
  { id: 'reydepentaculos', suit: 'pentacles', name: 'Rey de Pentáculos' },
];
